version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '5173:5173'
    volumes:
      - '.:/usr/src/app'
